import { getGroup } from "./resource-documentation";

// The kubernetes.io page explaining each kind, keyed by `<group>|<kind>` so every version shares it.
const conceptPaths: Readonly<Record<string, string>> = {
  "|Pod": "concepts/workloads/pods/",
  "|PodTemplate": "concepts/workloads/pods/#pod-templates",
  "|ReplicationController": "concepts/workloads/controllers/replicationcontroller/",
  "|Service": "concepts/services-networking/service/",
  "|ConfigMap": "concepts/configuration/configmap/",
  "|Secret": "concepts/configuration/secret/",
  "|Namespace": "concepts/overview/working-with-objects/namespaces/",
  "|Node": "concepts/architecture/nodes/",
  "|PersistentVolume": "concepts/storage/persistent-volumes/",
  "|PersistentVolumeClaim": "concepts/storage/persistent-volumes/",
  "|ServiceAccount": "concepts/security/service-accounts/",
  "|ResourceQuota": "concepts/policy/resource-quotas/",
  "|LimitRange": "concepts/policy/limit-range/",
  "apps|Deployment": "concepts/workloads/controllers/deployment/",
  "apps|ReplicaSet": "concepts/workloads/controllers/replicaset/",
  "apps|StatefulSet": "concepts/workloads/controllers/statefulset/",
  "apps|DaemonSet": "concepts/workloads/controllers/daemonset/",
  "batch|Job": "concepts/workloads/controllers/job/",
  "batch|CronJob": "concepts/workloads/controllers/cron-jobs/",
  "autoscaling|HorizontalPodAutoscaler": "concepts/workloads/autoscaling/horizontal-pod-autoscale/",
  "policy|PodDisruptionBudget": "concepts/workloads/pods/disruptions/",
  "policy|Eviction": "concepts/scheduling-eviction/api-eviction/",
  "networking.k8s.io|Ingress": "concepts/services-networking/ingress/",
  "networking.k8s.io|IngressClass": "concepts/services-networking/ingress/#ingress-class",
  "networking.k8s.io|NetworkPolicy": "concepts/services-networking/network-policies/",
  "networking.k8s.io|ServiceCIDR": "concepts/services-networking/cluster-ip-allocation/",
  "networking.k8s.io|IPAddress": "concepts/services-networking/cluster-ip-allocation/",
  "discovery.k8s.io|EndpointSlice": "concepts/services-networking/endpoint-slices/",
  "rbac.authorization.k8s.io|Role": "reference/access-authn-authz/rbac/",
  "rbac.authorization.k8s.io|ClusterRole": "reference/access-authn-authz/rbac/",
  "rbac.authorization.k8s.io|RoleBinding": "reference/access-authn-authz/rbac/",
  "rbac.authorization.k8s.io|ClusterRoleBinding": "reference/access-authn-authz/rbac/",
  "storage.k8s.io|StorageClass": "concepts/storage/storage-classes/",
  "storage.k8s.io|VolumeAttributesClass": "concepts/storage/volume-attributes-classes/",
  "storage.k8s.io|CSIStorageCapacity": "concepts/storage/storage-capacity/",
  "storage.k8s.io|CSIDriver": "concepts/storage/volumes/#csi",
  "storage.k8s.io|CSINode": "concepts/storage/volumes/#csi",
  "storage.k8s.io|VolumeAttachment": "concepts/storage/volumes/#csi",
  "scheduling.k8s.io|PriorityClass": "concepts/scheduling-eviction/pod-priority-preemption/",
  "node.k8s.io|RuntimeClass": "concepts/containers/runtime-class/",
  "coordination.k8s.io|Lease": "concepts/architecture/leases/",
  "admissionregistration.k8s.io|MutatingWebhookConfiguration": "reference/access-authn-authz/extensible-admission-controllers/",
  "admissionregistration.k8s.io|ValidatingWebhookConfiguration": "reference/access-authn-authz/extensible-admission-controllers/",
  "admissionregistration.k8s.io|ValidatingAdmissionPolicy": "reference/access-authn-authz/validating-admission-policy/",
  "admissionregistration.k8s.io|ValidatingAdmissionPolicyBinding": "reference/access-authn-authz/validating-admission-policy/",
  "admissionregistration.k8s.io|MutatingAdmissionPolicy": "reference/access-authn-authz/mutating-admission-policy/",
  "admissionregistration.k8s.io|MutatingAdmissionPolicyBinding": "reference/access-authn-authz/mutating-admission-policy/",
  "apiextensions.k8s.io|CustomResourceDefinition": "concepts/extend-kubernetes/api-extension/custom-resources/",
  "apiregistration.k8s.io|APIService": "concepts/extend-kubernetes/api-extension/apiserver-aggregation/",
  "certificates.k8s.io|CertificateSigningRequest": "reference/access-authn-authz/certificate-signing-requests/",
  "certificates.k8s.io|ClusterTrustBundle": "reference/access-authn-authz/certificate-signing-requests/#cluster-trust-bundles",
  "flowcontrol.apiserver.k8s.io|FlowSchema": "concepts/cluster-administration/flow-control/",
  "flowcontrol.apiserver.k8s.io|PriorityLevelConfiguration": "concepts/cluster-administration/flow-control/",
  "resource.k8s.io|DeviceClass": "concepts/scheduling-eviction/dynamic-resource-allocation/",
  "resource.k8s.io|ResourceClaim": "concepts/scheduling-eviction/dynamic-resource-allocation/",
  "resource.k8s.io|ResourceClaimTemplate": "concepts/scheduling-eviction/dynamic-resource-allocation/",
  "resource.k8s.io|ResourceSlice": "concepts/scheduling-eviction/dynamic-resource-allocation/",
  "authentication.k8s.io|TokenReview": "reference/access-authn-authz/authentication/",
  "authentication.k8s.io|TokenRequest": "reference/access-authn-authz/authentication/",
  "authentication.k8s.io|SelfSubjectReview": "reference/access-authn-authz/authentication/",
  "authorization.k8s.io|SubjectAccessReview": "reference/access-authn-authz/authorization/",
  "authorization.k8s.io|LocalSubjectAccessReview": "reference/access-authn-authz/authorization/",
  "authorization.k8s.io|SelfSubjectAccessReview": "reference/access-authn-authz/authorization/",
  "authorization.k8s.io|SelfSubjectRulesReview": "reference/access-authn-authz/authorization/",
};

export const getConceptUrl = (apiVersion: string, kind: string): string | undefined => {
  const path = conceptPaths[`${getGroup(apiVersion)}|${kind}`];

  return path ? `https://kubernetes.io/docs/${path}` : undefined;
};
